### PR TITLE
🩹fix: C SDK and OAPI-CLI return 0 (ok) when API call fail

### LINKED ISSUE #83: Exit code to 0 when api returns an error
Hello,

oapi-cli is exiting with a 0 exit status when the API returns an error, which was not the case with osc-cli. 
Is this intended? Because this can lead to some issues in our pipeline workflow or script execution.

```bash
$ oapi-cli raw-print DeleteSnapshot --SnapshotId snap-xxxxxx
{"Errors":[{"Type":"InvalidResource","Details":"The SnapshotId 'snap-xxxxxx' doesn't exist for the account 'xxxxxxxxxxxxx'.","Code":"5054"}],"ResponseContext":{"RequestId":"87dc13a6-1fbc-4eda-876b-b057eaff1928"}}
$ echo $?
0
```

```bash
$ osc-cli api DeleteSnapshot --SnapshotId snap-xxxxxx
osc_sdk.sdk.OscApiException: Error --> status = 400, code = 5054, code_type = InvalidResource, Reason = The SnapshotId 'snap-xxxxxx' doesn't exist for the account 'xxxxxxxxxxxxx'., request_id = b74ddc4a-b2a6-478e-8633-5c9ae1475894
$ echo $?
1
```

Thanks

### PR DESCRIPTION
**Pull request by jobs62**
HTTP Status code is ignored by default by libcurl

Closes [OAPI-CLI issue #83](https://github.com/outscale/oapi-cli/issues/83)

### CODE REVIEW

File: cognac_gen.sh [hunk 1]
```diff
@@ -485,17 +485,22 @@ EOF
...
+				puts(r.buf);
+			else if (cret)
+				fprintf(stderr, "fail to call $l: %s", curl_easy_strerror(cret));
+		     } else if (r.buf) {
 			     jobj = json_tokener_parse(r.buf);
 			     puts(json_object_to_json_string_ext(jobj,
 					JSON_C_TO_STRING_PRETTY | JSON_C_TO_STRING_NOSLASHESCAPE |
 					color_flag));
-		     }
+		     } else fprintf(stderr, "call to $l %s and returned a empty body", cret ? "failed" : "succeded");
```
Comment (outscale-rce) [inline cognac_gen.sh]: ..."Call to $l %s returned an empty body", cret ? "failed" : "succeeded");

**Review by outscale-rce — CHANGES_REQUESTED** [review]

File: cognac_gen.sh (hunk 1 above)
Comment (outscale-rce) [reply cognac_gen.sh]: succeeded
